CREATE TABLE User (
	UserID VARCHAR(40) NOT NULL PRIMARY KEY,
	Buyer_Rating INT DEFAULT -9001,
	Seller_Rating INT DEFAULT -9001,
	Location VARCHAR(100) DEFAULT "",
	Country VARCHAR(25) DEFAULT ""
);

CREATE TABLE Item (
	ItemID INT NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Currently DECIMAL(8,2) NOT NULL,
	Buy_Price DECIMAL(8,2) DEFAULT -9001,
	First_Bid DECIMAL(8,2) NOT NULL,
	Number_of_Bids INT NOT NULL,
	Location VARCHAR(100) NOT NULL,
	Latitude DECIMAL(16,6) DEFAULT -9001,
	Longitude DECIMAL(16,6) DEFAULT -9001,
	Country VARCHAR(25) NOT NULL,
	Started TIMESTAMP NOT NULL,
	Ends TIMESTAMP NOT NULL,
	SellerID VARCHAR(40) NOT NULL,
	Description VARCHAR(4000) DEFAULT "",
	FOREIGN KEY (SellerID)
		REFERENCES User(UserID)
		ON UPDATE CASCADE ON DELETE CASCADE 

);

CREATE TABLE Category (
	ItemID INT NOT NULL,
	Category VARCHAR(40) NOT NULL,
	PRIMARY KEY (ItemID, Category),
	FOREIGN KEY (ItemID)
		REFERENCES Item(ItemID)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Bid (
	ItemID INT NOT NULL,
	BidderID VARCHAR(40) NOT NULL,
	Time TIMESTAMP NOT NULL,
	Amount DECIMAL(8,2) NOT NULL,
	PRIMARY KEY (ItemID, BidderID, Time),
	FOREIGN KEY (ItemID)
		REFERENCES Item(ItemID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (BidderID)
		REFERENCES User(UserID)
		ON UPDATE CASCADE ON DELETE CASCADE
);
